'use client';
import React, { useState } from 'react';

export default function Home() {
  const [selectedCouple, setSelectedCouple] = useState<string>('');
    const [ratings, setRatings] = useState({
        outfit: 0,
            essence: 0,
                walk: 0,
                    chemistry: 0,
                        confidence: 0
                          });
                            const [submitted, setSubmitted] = useState<boolean>(false);

                              const handleRatingChange = (e: React.ChangeEvent<HTMLInputElement>) => {
                                  setRatings({
                                        ...ratings,
                                              [e.target.name]: parseInt(e.target.value) || 0
                                                  });
                                                    };

                                                      const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
                                                          e.preventDefault();
                                                              if (!selectedCouple) {
                                                                    alert('Please select a couple to rate.');
                                                                          return;
                                                                              }
                                                                                  console.log('Submitted Vote:', { couple: selectedCouple, ratings });
                                                                                      setSubmitted(true);
                                                                                        };

                                                                                          if (submitted) {
                                                                                              return (
                                                                                                    <main className="min-h-screen bg-orange-50 flex items-center justify-center p-4">
                                                                                                            <div className="bg-white p-8 rounded-lg shadow-xl text-center max-w-md w-full">
                                                                                                                      <h2 className="text-2xl font-bold text-green-700 mb-4">Thank You!</h2>
                                                                                                                                <p className="text-gray-700">Your vote for the BMKA Kerala Thanima Couple Title 2026 has been recorded.</p>
                                                                                                                                          <button 
                                                                                                                                                      onClick={() => setSubmitted(false)}
                                                                                                                                                                  className="mt-6 bg-orange-600 text-white px-6 py-2 rounded-full font-bold hover:bg-orange-700"
                                                                                                                                                                            >
                                                                                                                                                                                        Vote Again
                                                                                                                                                                                                  </button>
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                    );
                                                                                                                                                                                                                      }

                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                            <main className="min-h-screen bg-orange-50 py-10 px-4 sm:px-6 lg:px-8">
                                                                                                                                                                                                                                  <div className="max-w-2xl mx-auto bg-white rounded-xl shadow-xl overflow-hidden border border-orange-100">
                                                                                                                                                                                                                                          <div className="bg-gradient-to-r from-orange-600 to-red-700 px-6 py-8 text-center text-white">
                                                                                                                                                                                                                                                    <h1 className="text-3xl font-bold mb-2">BMKA Kerala Thanima</h1>
                                                                                                                                                                                                                                                              <h2 className="text-xl font-semibold">Tharadambathikal 2026 - Audience Poll</h2>
                                                                                                                                                                                                                                                                        <p className="mt-2 text-sm opacity-90">A Celebration of Kerala Culture, Style & Togetherness</p>
                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                        <form onSubmit={handleSubmit} className="p-6 sm:p-8 space-y-8">
                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                              <label className="block text-lg font-bold text-gray-800 mb-3">Select Couple</label>
                                                                                                                                                                                                                                                                                                                          <select 
                                                                                                                                                                                                                                                                                                                                        value={selectedCouple} 
                                                                                                                                                                                                                                                                                                                                                      onChange={(e: React.ChangeEvent<HTMLSelectElement>) => setSelectedCouple(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                    className="w-full border border-gray-300 p-3 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-orange-500 text-gray-900"
                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                              <option value="">-- Choose a Couple --</option>
                                                                                                                                                                                                                                                                                                                                                                                                            <option value="Couple 1">Couple 1</option>
                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="Couple 2">Couple 2</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="Couple 3">Couple 3</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="Couple 4">Couple 4</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-lg font-bold text-gray-800 border-b pb-2">Judgement Criteria</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="flex justify-between text-gray-700 font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>Outfit & Presentation (25%)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>{ratings.outfit}/25</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="range" name="outfit" min="0" max="25" value={ratings.outfit} onChange={handleRatingChange} className="w-full accent-orange-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label className="flex justify-between text-gray-700 font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>Kerala Ethnic Essence (20%)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>{ratings.essence}/20</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input type="range" name="essence" min="0" max="20" value={ratings.essence} onChange={handleRatingChange} className="w-full accent-orange-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="flex justify-between text-gray-700 font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>Walk & Stage Presence (20%)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>{ratings.walk}/20</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="range" name="walk" min="0" max="20" value={ratings.walk} onChange={handleRatingChange} className="w-full accent-orange-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="flex justify-between text-gray-700 font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>Togetherness & Chemistry (20%)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>{ratings.chemistry}/20</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="range" name="chemistry" min="0" max="20" value={ratings.chemistry} onChange={handleRatingChange} className="w-full accent-orange-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="flex justify-between text-gray-700 font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>Confidence & Overall Impact (15%)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>{ratings.confidence}/15</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="range" name="confidence" min="0" max="15" value={ratings.confidence} onChange={handleRatingChange} className="w-full accent-orange-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-orange-100 p-4 rounded-lg flex justify-between items-center text-lg font-bold text-orange-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>Total Audience Score:</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>{ratings.outfit + ratings.essence + ratings.walk + ratings.chemistry + ratings.confidence} / 100</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" className="w-full bg-green-700 hover:bg-green-800 text-white font-bold py-4 rounded-lg shadow-md transition duration-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Submit Rating
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  